### ISSUE TITLE
Bug in STRexpansion (line 232)

### ISSUE THREAD

**Issue by lfpaulin** [DamarisLa/STRsimulator#24]
In some cases the value of self.max_reduction is not assigned before usage and we have an error, this is likely when there is going to be **no** expansion
```
FAILURE
lpaz@lpaz-GF63-10SC: simiSTR> bash run-test.sh 
[INFO] old length 50818468 
Traceback (most recent call last):
  File "simiSTR.py", line 460, in <module>
    sim.main_manipulation()
  File "simiSTR.py", line 372, in main_manipulation
    partOfSeqNew, expBaseNrchange = self.STRexpansion(numberOfRepeats,patternLen,pattern)
  File "simiSTR.py", line 232, in STRexpansion
    if self.max_reduction <= numberOfRepeats:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

SUCCESS
lpaz@lpaz-GF63-10SC: simiSTR> bash run-test.sh 
[INFO] old length 50818468 
[INFO] new length sequence: 50818468 
[INFO] new length sequence: 50818469 
[WARNING] Not found regions (unchanged): 0 
```

**Comment by DamarisLa** [comment]
Should work now again
